var __juice_bar_data = {
12:["pressurized potion of perspicacity","flask of porquoise juice","gamer slurry"],
17:["lotion of coldness","gremlin juice","little red jam"],
18:["cranberry cordial","jug of hamethyst juice","salamander slurry"],
21:["Mer-kin cooljuice","bottle of pirate juice","sea grease"],
22:["blood of the Wereseal","Knob Goblin steroids","blackberry polite"],
23:["hair spray","fish-liver oil","bubblin' chemistry solution"],
25:["jar of \"Creole Lady\" marrrmalade","Gearhead Goo","oil of oiliness"],
26:["bubblin' chemistry solution","Mer-kin cooljuice","bag of pygmy blood"],
27:["pygmy adder oil","Knob Goblin perfume","Polysniff Perfume"],
28:["Gearhead Goo","Black Body™ spray","concoction of clumsiness"],
29:["cordial of concentration","papotion of papower","probability potion"],
30:["pressurized potion of perception","cologne of contempt","blackberry polite"],
31:["cordial of concentration","Ben-Gal™ Balm","spooky eyeliner"],
32:["ant agonist","Oil of Parrrlay","Stephen's secret formula"],
33:["lotion of sleaziness","pressurized potion of pulchritude","embezzler's oil"],
34:["pressurized potion of pulchritude","oil of expertise","weremoose spit"],
35:["philter of phorce","potion of temporary gr8tness","Knob Goblin pet-buffing spray"],
36:["Polysniff Perfume","pressurized potion of puissance","Redeye™ Eyedrops"],
37:["vial of The Glistening","gremlin juice","eyedrops of the ermine"],
38:["Knob Goblin love potion","little red jam","bottle of antifreeze"],
39:["potion of potency","Tears of the Quiet Healer","papotion of papower"],
40:["bag of pygmy blood","oil of oiliness","steampunk potion"],
41:["Mick's IcyVapoHotness Rub","orcish nailing lube","cordial of concentration"],
42:["cologne of contempt","black eyedrops","vial of blood simple syrup"],
43:["Mer-kin cooljuice","pygmy adder oil","little red jam"],
44:["blood of the Wereseal","Knob Goblin Mutagen","Redeye™ Eyedrops"],
45:["steampunk potion","lotion of spookiness","vial of hamethyst juice"],
46:["flask of rainwater","Lewd Lemmy Hair Oil","eyedrops of newt"],
47:["electric copperhead potion","possibility potion","super-spiky hair gel"],
48:["bottle of antifreeze","Eau de Guaneau","Tears of the Quiet Healer"],
49:["Stephen's secret formula","Texas tea","Knob Goblin pet-buffing spray"],
50:["clove-flavored lip balm","bubblin' chemistry solution","bag of pygmy blood"],
51:["eyedrops of the ermine","Gearhead Goo","orcish nailing lube"],
52:["bottle of pirate juice","tears of the Quiet Healer","little red jam"],
53:["cologne of contempt","tomato juice of powerful power","Connery's Elixir of Audacity"],
54:["Lewd Lemmy Hair Oil","gremlin mutagen","jug of porquoise juice"],
55:["Hawking's Elixir of Brilliance","fabric hardener","Mer-kin smartjuice"],
56:["lotion of hotness","Mer-kin cooljuice","Knob Goblin steroids"],
57:["Wax Flask","ectoplasm au jus","cranberry cordial"],
58:["lotion of coldness","tiny canopic jar","extra-potent gremlin mutagen"],
59:["bottle of rhinoceros hormones","weremoose spit","pygmy pygment"],
60:["oil of expertise","extra-potent gremlin mutagen","concentrated cordial of concentration"],
61:["potent potion of potency","weremoose spit","Knob Goblin eyedrops"],
62:["eyedrops of the ermine","Mer-kin fastjuice","Ben-Gal™ Balm"],
63:["pressurized potion of perception","concentrated cordial of concentration","blackberry polite"],
64:["jug of porquoise juice","flask of rainwater","lotion of stench"],
65:["Eau de Guaneau","concentrated garbage juice","potion of temporary gr8tness"],
66:["concoction of clumsiness","tube of dread wax","Redeye™ Eyedrops"],
67:["knob goblin love potion","super-spiky hair gel","unholy water"],
68:["pygmy pygment","eyedrops of newt","glowing syringe"],
69:["lynyrd musk","unholy water","spooky eyeliner"],
70:["spooky eyeliner","deodorant","Knob Goblin nasal spray"],
71:["Knob Goblin pet-buffing spray","handsomeness potion","Ben-Gal™ Balm"],
72:["cranberry cordial","vial of baconstone juice","perfume of prejudice"],
73:["glass of warm milk","vial of porquoise juice","henna face paint"],
74:["Mer-kin cooljuice","potent potion of potency","blackberry polite"],
75:["perfume of prejudice","Hawking's Elixir of Brilliance","eyedrops of the ocelot"],
76:["old rosewater cream","Connery's Elixir of Audacity","pressurized potion of puissance"],
77:["electric copperhead potion","clove-flavored lip balm","vial of swamp vapors"],
78:["glowing syringe","concentrated garbage juice","vial of The Glistening"],
79:["reodorant","Texas tea","flask of hamethyst juice"],
80:["lotion of hotness","unholy water","oil of expertise"],
81:["henna face paint","Mer-kin smartjuice","flask of hamethyst juice"],
82:["Ben-Gal™ Balm","glass of warm milk","jar of \"Creole Lady\" marrrmalade"],
83:["orcish hand lotion","Knob Goblin steroids","oil of expertise","Unrestricted,"],
83:["orcish hand lotion","Knob Goblin steroids","oil of expertise"],
84:["extra-potent gremlin mutagen","bubblin' chemistry solution","papotion of papower"],
85:["jug of baconstone juice","eyedrops of newt","cordial of concentration"],
86:["pressurized potion of pulchritude","Mer-kin fastjuice","seal-brain elixir"],
87:["turtle pheromones","Knob Goblin perfume","Wax Flask"],
88:["vial of swamp vapors","eyedrops of newt","weremoose spit"],
89:["bottle of Mystic Shell","pygmy pygment","hair spray"],
90:["fake blood","fabric hardener","Connery's Elixir of Audacity"],
91:["super-spiky hair gel","tomato juice of powerful power","reodorant"],
92:["cyclops eyedrops","bottle of Mystic Shell","Black No. 2"],
93:["seal-brain elixir","Stephen's secret formula","jug of baconstone juice"],
94:["eyedrops of newt","flask of baconstone juice","sea grease"],
95:["vial of The Glistening","little red jam","vial of hamethyst juice"],
96:["pressurized potion of perception","blood of the Wereseal","seal-brain elixir"],
97:["turtle pheromones","gremlin mutagen","vial of swamp vapors"],
98:["hair spray","lotion of stench","sea grease"],
99:["lynyrd skinner toothblack","Knob Goblin eyedrops","extra-potent gremlin mutagen"],
100:["eyedrops of the ocelot","weremoose spit","potent potion of potency"],
101:["flask of baconstone juice","vial of hamethyst juice","lotion of sleaziness"],
102:["vial of porquoise juice","steampunk potion","lotion of coldness"],
103:["Mick's IcyVapoHotness Rub","pressurized potion of puissance","concoction of clumsiness"],
104:["old rosewater cream","super-spiky hair gel","lotion of coldness"],
105:["Redeye™ Eyedrops","eyedrops of newt","Knob Goblin Mutagen"],
106:["pygmy pygment","vial of swamp vapors","zombie hollandaise"],
107:["can of black paint","pygmy adder oil","oil of stability"],
108:["ectoplasm au jus","gremlin juice","clove-flavored lip balm"],
109:["cologne of contempt","electric copperhead potion","spooky eyeliner"],
110:["eyedrops of the ocelot","gremlin juice","Mer-kin fastjuice"],
111:["bottle of pirate juice","milk of magnesium","gremlin mutagen"],
112:["possibility potion","potent potion of potency","lotion of stench"],
113:["jar of \"Creole Lady\" marrrmalade","lotion of spookiness","pressurized potion of pulchritude"],
114:["handsomeness potion","Mer-kin fastjuice","Knob Goblin pet-buffing spray"],
115:["potion of temporary gr8tness","pressurized potion of perspicacity","tube of dread wax"],
116:["blackberry polite","Black No. 2","jar of \"Creole Lady\" marrrmalade"],
117:["Hawking's Elixir of Brilliance","ointment of the occult","little red jam"],
118:["oil of slipperiness","Mer-kin strongjuice","mariachi toothpaste"],
119:["pressurized potion of pulchritude","Knob Goblin steroids","lynyrd musk"],
120:["Mer-kin smartjuice","clove-flavored lip balm","Ben-Gal™ Balm"],
121:["oil of slipperiness","lotion of hotness","Ben-Gal™ Balm"],
122:["pressurized potion of proficiency","probability potion","perfume of prejudice"],
123:["blood of the Wereseal","perfume of prejudice","glass of warm milk"],
124:["jar of \"Creole Lady\" marrrmalade","flask of baconstone juice","Mer-kin ragejuice"],
125:["possibility potion","bubblin' chemistry solution","embezzler's oil"],
126:["Knob Goblin perfume","ectoplasm au jus","possibility potion"],
127:["Ben-Gal™ Balm","electric copperhead potion","orcish nailing lube"],
128:["oil of oiliness","cyclops eyedrops","jar of \"Creole Lady\" marrrmalade"],
129:["Mer-kin cooljuice","Knob Goblin eyedrops","panty raider camouflage"],
130:["old rosewater cream","jug of porquoise juice","flask of porquoise juice"],
131:["bottle of antifreeze","pressurized potion of proficiency","fish-liver oil"],
132:["lynyrd musk","Ben-Gal™ Balm","bag of pygmy blood"],
133:["Connery's Elixir of Audacity","potent potion of potency","milk of magnesium"],
134:["black facepaint","handsomeness potion","lotion of coldness"],
135:["pec oil","serum of sarcasm","jug of porquoise juice"],
136:["pressurized potion of puissance","vial of The Glistening","black facepaint"],
137:["pygmy adder oil","bubblin' chemistry solution","bottle of rhinoceros hormones"],
138:["Polysniff Perfume","libation of liveliness","steampunk potion"],
139:["gremlin juice","fish-liver oil","vial of The Glistening"],
140:["turtle pheromones","cranberry cordial","bottle of antifreeze"],
141:["Black Body™ spray","steampunk potion","Lewd Lemmy Hair Oil"],
142:["papotion of papower","serum of sarcasm","Ben-Gal™ Balm"],
144:["lotion of coldness","Knob Goblin pet-buffing spray","orcish nailing lube"],
145:["little red jam","Bangyomaman battle juice","henna face paint"],
146:["Connery's Elixir of Audacity","fake blood","Knob Goblin perfume"],
147:["Texas tea","Knob Goblin perfume","black facepaint"],
149:["pressurized potion of perspicacity","black facepaint","ant agonist"],
150:["steampunk potion","serum of sarcasm","flask of rainwater"],
151:["Redeye™ Eyedrops","Texas tea","fish-liver oil"],
152:["Knob Goblin perfume","Knob Goblin love potion","pressurized potion of perception"],
153:["concentrated cordial of concentration","steampunk potion","Mer-kin fastjuice"],
154:["glass of gnat milk","milk of magnesium","eyedrops of the ermine"],
156:["potion of potency","Tears of the Quiet Healer","bottle of pirate juice"],
159:["pressurized potion of pulchritude","gamer slurry","deodorant"],
161:["vial of porquoise juice","Tears of the Quiet Healer","pygmy pygment"],
164:["pygmy pygment","vial of The Glistening","potion of potency"],
166:["serum of sarcasm","Black Body™ spray","electric copperhead potion"],
169:["cordial of concentration","jug of hamethyst juice","Eau de Guaneau"],
171:["Wax Flask","steampunk potion","sea grease"],
176:["orcish hand lotion","pressurized potion of perspicacity","hair spray"],
181:["vial of blood simple syrup","reodorant","Knob Goblin Mutagen"],
186:["ant agonist","glass of gnat milk","Knob Goblin perfume"],
191:["possibility potion","serum of sarcasm","jug of baconstone juice"],
193:["fabric hardener","pressurized potion of perception","vial of hamethyst juice"],
198:["tiny canopic jar","oil of stability","steampunk potion"],
203:["pressurized potion of perspicacity","cyclops eyedrops","eyedrops of newt"],
208:["pressurized potion of pulchritude","vial of hamethyst juice","glass of warm milk"],
209:["little red jam","flask of porquoise juice","ointment of the occult"],
213:["deodorant","vial of The Glistening","fish-liver oil"],
214:["gamer slurry","potent potion of potency","embezzler's oil"],
216:["blackberry polite","zombie hollandaise","vial of The Glistening"],
218:["pressurized potion of perspicacity","Knob Goblin steroids","Knob Goblin love potion"],
219:["Gearhead Goo","cranberry cordial","potent potion of potency"],
221:["super-spiky hair gel","Lewd Lemmy Hair Oil","old rosewater cream"],
223:["gremlin mutagen","hair spray","clove-flavored lip balm"],
224:["super-spiky hair gel","fabric hardener","artisanal hand-squeezed wheatgrass juice"],
226:["fake blood","concentrated garbage juice","black eyedrops"],
228:["can of black paint","unholy water","flask of hamethyst juice"],
229:["lotion of coldness","blackberry polite","Polysniff Perfume"],
231:["oil of slipperiness","Mer-kin smartjuice","spooky eyeliner"],
233:["Mick's IcyVapoHotness Rub","Ben-Gal™ Balm ","pressurized potion of pulchritude"],
236:["salamander slurry","papotion of papower","tube of dread wax"],
238:["eyedrops of the ocelot","ectoplasm au jus","eyedrops of the ermine"],
243:["Knob Goblin steroids","fake blood","spooky eyeliner"],
248:["Tears of the Quiet Healer","black facepaint","vial of swamp vapors"],
253:["salamander slurry","weremoose spit","super-spiky hair gel"],
258:["Polysniff Perfume","Mer-kin smartjuice","perfume of prejudice"],
263:["bag of pygmy blood","lynyrd musk","potion of temporary gr8tness"],
268:["Knob Goblin steroids","gremlin mutagen","clove-flavored lip balm"],
273:["zombie hollandaise","oil of slipperiness","Knob Goblin love potion"],
278:["oil of slipperiness","weremoose spit","cyclops eyedrops"],
283:["little red jam","Connery's Elixir of Audacity","Mick's IcyVapoHotness Rub"]
};

function DailiesGenerateJuiceBar(path_id, class_id, day_number)
{
	var output_string = "";
	var id = path_id * 3 + day_number * 5 + class_id * 7;

	var data = __juice_bar_data[id];
	if (data == undefined)
		return [];
	output_string = data.join(", ");
	return ["Chateau Mantegna Juice Bar", output_string];
}
__dailies_generation_functions.push(DailiesGenerateJuiceBar);